### ISSUE TITLE
Sugerencia relé

### ISSUE THREAD

**Issue by manolodd** [miguelangelcasanova/codos#15]
Buenas,

Buen trabajo! Como sugerencia se podría preparar el código para disparar un relé tomando como referencia dos valores (como ocurre con las bombas de extracción de agua). Por si en el aula se dispone de un extractor helicoidal para ayudar a ventilar. Así se podría encender automáticamente cuando se llega al tope y estar en funcionamiento hasta que se llegue al nivel "óptimo".

Un saludo.

**Comment by miguelangelcasanova** [comment]
Por supuesto, es tan sencillo como poner en alto/bajo un pin cuando se llegue al valor prefijado, aunque para evitar problemas sería más interesante introducir unos valores de histéresis. Si te animas a hacer el código lo añadimos al repo y sino sabes proponlo por el grupo de Telegram y te ayudamos.
