### ISSUE TITLE
Cambio de detector de CO2

### ISSUE THREAD

**Issue by BySergy-Uny** [miguelangelcasanova/codos#3]
He encontrado este que es mucho mas barato haber si se podría integrar y es más fiable.

[enlace del detector de CO2](https://circuit.rocks/infrared-co2-sensor-analog-for-arduino-0-5000-ppm-gravity.html)

**Comment by miguelangelcasanova** [comment]
Tiene muy buena pinta... claro que podría integrarse. Gracias por el enlace.
