### ISSUE TITLE
Bosh BME680 vs CCS811 + BME280

### ISSUE THREAD

**Issue by ricardoper** [miguelangelcasanova/codos#5]
Buenos días,

Antes de nada, indicar que se trata de una buena idea para intentar de algún modo ayudar en estos momentos de dificultades.

Entiendo que la discusión de un o otro sensor es muy relativa y siempre hay pros y contras en todas las decisiones, pero creo que se podría optar por un sensor más completo por un precio igual o inferior en base a las características deseadas.

Para tener un eCO2 lo más fiable posible, añadir datos como temperatura y humedad sería lo más idóneo. Este tipo de compensaciones es muy importantes dependiendo de las estaciones y ciudades en que se pueda usar este dispositivo. Sé que tenéis como opcional el sensor BME280 de Bosch para estos casos pero a final el opcional siempre cae en el olvido.

Yo propongo el uso del sensor *[BME680](https://www.bosch-sensortec.com/products/environmental-sensors/gas-sensors-bme680/)* por las siguientes razones:
* Es prácticamente idéntico al sensor CCS811 pero cuenta con más datos ambientales (especialmente temperatura). Incluso con un coste prácticamente igual.
* El coste seria más bajo si sumamos los sensores CCS811 + BME280 manteniendo la funcionalidad de ambos. El opcional dejaría de tener sentido.
* El BME680 también se puede comprar en AliExpress en formato Breakout, [CJMCU-680](https://es.aliexpress.com/wholesale?trafficChannel=main&d=y&CatId=0&SearchText=BME680&ltype=wholesale&isFreeShip=n&SortType=price_asc&page=1&groupsort=1).
* Si un día este proyecto cuaja y haya que realizar una PCB definitiva, este sensor ocupará muy poco espacio en comparación con el uso de dos sensores (CCS811 + BME280).
* El sensor CCS811 ya no esta recomendado para nuevos proyectos en vista que la compañía que los produce/desarrolla ha sido comprada y su futuro es incierto.

A nivel de librerías, no creo que sea un problema ya que tanto [Adafruit](https://github.com/adafruit/Adafruit_BME680) como la pagina de [Bosch](https://github.com/BoschSensortec/BME680_driver) las tienen disponibles.

Espero que esta información sea útil para el proyecto,
[Ricardo Pereira](https://ricardopereira.es/).

**Comment by miguelangelcasanova** [comment]
Hola Ricardo, gracias por tu interés en el proyecto.
Te comento un poco el porqué de mis decisiones. Inicialmente plantee
únicamente el uso del CCS811 para medir el eCO2 y los TVOC. En realidad de
lo que se trataba era exactamente de eso.

La cuestión es que no es fácil para una escuela o instituto conseguir
presupuesto para montar decenas de sensores. por lo que el uso del
BME280 se puso como opcional.

Ciertamente el uso de senosres mejores como  el BME680 permite obtener
mejores resultados; pero el CCS811 no puedes sustituirlo por el BME680,
aunque sí el BME280.

En cualquier caso, los datos ambientales no resultan tan importantes para
la aplicación que se pretende y resulta mucho más fácil de localizar el
BME280 (o el BMP280) que el BME680, de forma local. De todas formas el uso
de uno u otro no cambia la funcionalidad del sistema.

La elección de la utilización del CCS811 no es más que una de las posibles
opciones. De lo que se trata es de que los usuarios sean conscientes de la
importancia de la ventilación de las aulas y espacios de trabajo.Si
prefieres utilizar otro sensor tampoco hay problema alguno. El kit de la
cuestión sigue siendo saber los valores que definen cuándo hay que ventilar
para un aula o espacio determinado en función del tamaño de la sala, el
número de personas... es ahí dónde debemos centrar los esfuerzos para
encontrar los mejores valores.

Un saludo, Miguel Ángel.

**Comment by ricardoper** [comment]
Hola Miguel Ángel,

Muchas gracias por la respuesta tan detallada y por ilustrar las ideas en que se basan este proyecto.

En base a tu respuesta, cerraré este Issue.

Un saludo,
Ricardo Pereira.
